server:
  port: 8888
  servlet:
    context-path: /api/petconnet

spring:
  application:
    name: petconnet
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://localhost:3306/petconnet?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    web: DEBUG