openapi: 3.0.3
info:
  title: API REST Pets
  description: API REST Pets
  version: 1.0.0
servers:
  - url: 'http://localhost:8888/api/petconnet'
tags:
  - name: pet
    description: 'Tudo sobre seu Pet'
paths:
  /pets/register:
    post:
      tags:
        - pet
      summary: Cadastrar Pet
      description: Adicionar novo animal de estimação
      operationId: registerPet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
      responses:
        '201':
          description: 'Pet cadastrado com sucesso'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetResponse'
components:
  schemas:
    PetRequest:
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: 'Bob'
    PetResponse:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 'Bob'

  
